from myapp import SomeDataset

from PyQt5.QtWidgets import QFileDialog,QCheckBox,QGridLayout,QTabWidget,QApplication,QWidget,QLabel,QPushButton,QMainWindow,QLineEdit,QComboBox,QToolTip
from PyQt5 import QtGui, QtCore
from PyQt5.QtGui import QFont
import numpy as np
from PyQt5.QtCore import pyqtSlot, Qt
import matplotlib.pyplot as plt
from matplotlib.figure import Figure
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT as NavigationToolbar
from scipy.signal import find_peaks
from mpl_toolkits.basemap import Basemap
import sys
from mpl_toolkits.axes_grid1 import make_axes_locatable
class App(QMainWindow):
    def __init__(self):
        super().__init__()
        self.initUI()
        self.tempArray = []
        self.dates = []
        self.level = []
        self.longtitude = []
        self.latitude = []

    def initUI(self):
        QToolTip.setFont(QFont('SansSerif', 10))

        ## СВОЙСТВА КНОПОК #############################

        self.btnDwnld = QPushButton('Загрузка', self)
        self.btnDwnld.move(40, 230)
        self.btnDwnld.resize(100, 30)
        # self.btnDwnld.clicked.connect(self.download)
        # self.btnDwnld.clicked.connect(self.otrisovka1)
        # self.btnDwnld.clicked.connect(self.otrisovka2)
        self.btnExit = QPushButton('Выход', self)
        self.btnExit.move(40, 600)
        self.btnExit.resize(50, 50)
        # self.btnExit.clicked.connect(self.exit)
        self.btnMap = QPushButton('Карта', self)
        self.btnMap.move(150, 250)
        self.btnMap.resize(100, 20)
        # self.btnMap.clicked.connect(self.dateMap)
        # self.btnMap.clicked.connect(self.dateMap2)
        # self.btnMap.clicked.connect(self.dateMap3)
        self.btnGraph = QPushButton('График', self)
        self.btnGraph.move(40, 270)
        self.btnGraph.resize(60, 30)
        # self.btnGraph.clicked.connect(self.timePlot)
        self.btnPrevMap = QPushButton('<', self)
        self.btnPrevMap.move(150, 270)
        self.btnPrevMap.resize(30, 30)
        # self.btnPrevMap.clicked.connect(self.PrevMap)
        # self.btnPrevMap.clicked.connect(self.dateMap)
        # self.btnPrevMap.clicked.connect(self.dateMap2)
        # self.btnPrevMap.clicked.connect(self.dateMap3)
        self.btnNextMap = QPushButton('>', self)
        self.btnNextMap.move(180, 270)
        self.btnNextMap.resize(30, 30)
        # self.btnNextMap.clicked.connect(self.NextMap)
        # self.btnNextMap.clicked.connect(self.dateMap)
        # self.btnNextMap.clicked.connect(self.dateMap2)
        # self.btnNextMap.clicked.connect(self.dateMap3)

        #### СВОЙСТВА ТЕКСТОВ ####################
        self.labVys1 = QLabel('Высота(1), ГПа', self)
        self.labVys1.resize(self.labVys1.sizeHint())
        self.labVys1.move(40, 30)
        self.labVys2 = QLabel('Высота(2), ГПа', self)
        self.labVys2.resize(self.labVys2.sizeHint())
        self.labVys2.move(40, 60)
        self.labShir1 = QLabel('Широта(График)', self)
        self.labShir1.resize(self.labShir1.sizeHint())
        self.labShir1.move(40, 90)
        self.labDolg1 = QLabel('Долгота(График)', self)
        self.labDolg1.resize(self.labDolg1.sizeHint())
        self.labDolg1.move(40, 120)
        self.labShir2 = QLabel('Широта(Карта)', self)
        self.labShir2.resize(self.labShir2.sizeHint())
        self.labShir2.move(40, 150)
        self.labDolg2 = QLabel('Долгота(Карта)', self)
        self.labDolg2.resize(self.labDolg2.sizeHint())
        self.labDolg2.move(40, 180)
        self.labLTA = QLabel('LTA', self)
        self.labLTA.resize(70, 20)
        self.labLTA.move(250, 30)
        self.labSTA = QLabel('STA', self)
        self.labSTA.resize(70, 20)
        self.labSTA.move(250, 90)

        ########### СВОЙСТВА  ОКОН ДЛЯ ТЕКСТА ##############
        self.textLTA = QLineEdit(self)
        self.textLTA.move(250, 60)
        self.textLTA.setText('105')
        self.textLTA.resize(50, 20)
        self.textSTA = QLineEdit(self)
        self.textSTA.move(250, 120)
        self.textSTA.setText('21')
        self.textSTA.resize(50, 20)

        ################ СВОЙСТВА ТАБЛИЦ   #####################
        self.boxLevel1 = QComboBox(self)
        self.boxLevel1.move(150, 30)
        self.boxLevel1.resize(70, 20)
        self.boxLevel2 = QComboBox(self)
        self.boxLevel2.move(150, 60)
        self.boxLevel2.resize(70, 20)
        self.boxLat1 = QComboBox(self)
        self.boxLat1.move(150, 90)
        self.boxLat1.resize(70, 20)
        self.boxLon1 = QComboBox(self)
        self.boxLon1.move(150, 120)
        self.boxLon1.resize(70, 20)
        self.boxLat2 = QComboBox(self)
        self.boxLat2.move(150, 150)
        self.boxLat2.resize(70, 20)
        self.boxLon2 = QComboBox(self)
        self.boxLon2.move(150, 180)
        self.boxLon2.resize(70, 20)
        self.boxDates = QComboBox(self)
        self.boxDates.move(150, 230)
        self.boxDates.resize(100, 20)
        self.boxDates.view().setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)

        ############# ОСНОВНЫЕ СВОЙСТВА ОСНОВНЫХ ВКЛАДОК ###############

        self.tabs = QTabWidget(self)
        self.tabs.resize(950, 700)
        self.tabs.move(320, 0)

        self.tab1 = QWidget(self)
        self.tab2 = QWidget(self)
        self.tab3 = QWidget(self)
        self.tab4 = QWidget(self)
        self.tab5 = QWidget(self)
        self.tab6 = QWidget(self)

        self.tabs.addTab(self.tab1, "Карта(Широта/Долгота)")
        self.tabs.addTab(self.tab2, "Карта(Широта/Высота)")
        self.tabs.addTab(self.tab3, "Карта(Долгота/Высота)")
        self.tabs.addTab(self.tab4, "Временной График;STA/LTA")
        self.tabs.addTab(self.tab5, "Временной График(Широта/Долгота)")
        self.tabs.addTab(self.tab6, 'Сохранение Графиков')

        self.tab1.layout = QGridLayout(self.tab1)
        self.tab1.setLayout(self.tab1.layout)
        self.tab2.layout = QGridLayout(self.tab2)
        self.tab2.setLayout(self.tab2.layout)
        self.tab3.layout = QGridLayout(self.tab3)
        self.tab3.setLayout(self.tab3.layout)
        self.tab4.layout = QGridLayout(self.tab4)
        self.tab4.setLayout(self.tab4.layout)
        self.tab5.layout = QGridLayout(self.tab5)
        self.tab5.setLayout(self.tab5.layout)
        self.tab6.layout = QGridLayout(self.tab6)
        self.tab6.setLayout(self.tab6.layout)

        self.tab5.layout.setRowStretch(0, 1)
        self.tab5.layout.setRowStretch(1, 4)
        self.tab5.layout.setRowStretch(4, 4)
        self.tab5.layout.setRowStretch(3, 1)
        self.tab5.layout.setRowStretch(6, 1)

        ########### ВКЛАДКА: Временной график (Широта/Долгота) #################

        self.labDate = QLabel('Даты', self)
        self.tab5.layout.addWidget(self.labDate, 0, 0, 1, 1)
        self.boxDates2 = QComboBox(self)
        self.boxDates2.view().setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.tab5.layout.addWidget(self.boxDates2, 0, 1, 1, 4)
        self.boxDates3 = QComboBox(self)
        self.boxDates3.view().setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.tab5.layout.addWidget(self.boxDates3, 0, 5, 1, 4)
        self.lablat = QLabel('Широта', self)
        self.tab5.layout.addWidget(self.lablat, 0, 9, 1, 1)
        self.boxLat3 = QComboBox(self)
        self.tab5.layout.addWidget(self.boxLat3, 0, 10, 1, 1)
        self.lablon = QLabel('Долгота', self)
        self.tab5.layout.addWidget(self.lablon, 0, 11, 1, 1)
        self.boxLon3 = QComboBox(self)
        self.tab5.layout.addWidget(self.boxLon3, 0, 12, 1, 1)
        self.btnMap2 = QPushButton('График', self)
        self.tab5.layout.addWidget(self.btnMap2, 0, 13, 1, 2)
        # self.btnMap2.clicked.connect(self.latlonMap)
        self.cmapBox2 = QComboBox(self)
        self.tab5.layout.addWidget(self.cmapBox2, 0, 15, 1, 2)

        ########### ВКЛАДКА: Сохранение графиков #################

        self.labSave1 = QLabel('Карта(Широта/Долгота)', self)
        self.tab6.layout.addWidget(self.labSave1, 0, 0)
        self.textSave1 = QLineEdit(self)
        self.textSave1.setText('file1')
        self.tab6.layout.addWidget(self.textSave1, 0, 1)
        self.boxFormats1 = QComboBox(self)
        self.tab6.layout.addWidget(self.boxFormats1, 0, 2)
        self.textDPI = QLineEdit(self)
        self.textDPI.setText('300 dpi')
        self.tab6.layout.addWidget(self.textDPI, 0, 3)
        self.btnSaveMap1 = QPushButton('Сохранить', self)
        self.tab6.layout.addWidget(self.btnSaveMap1, 0, 4)
        # self.btnSaveMap1.clicked.connect(self.Save1)
        self.labSave2 = QLabel('Карта(Широта/Высота)', self)
        self.tab6.layout.addWidget(self.labSave2, 1, 0)
        self.textSave2 = QLineEdit(self)
        self.textSave2.setText('file2')
        self.tab6.layout.addWidget(self.textSave2, 1, 1)
        self.boxFormats2 = QComboBox(self)
        self.tab6.layout.addWidget(self.boxFormats2, 1, 2)
        self.textDPI2 = QLineEdit(self)
        self.textDPI2.setText('300 dpi')
        self.tab6.layout.addWidget(self.textDPI2, 1, 3)
        self.btnSaveMap2 = QPushButton('Сохранить', self)
        self.tab6.layout.addWidget(self.btnSaveMap2, 1, 4)
        # self.btnSaveMap2.clicked.connect(self.Save2)
        self.labSave3 = QLabel('Карта(Долгота/Высота)', self)
        self.tab6.layout.addWidget(self.labSave3, 2, 0)
        self.textSave3 = QLineEdit(self)
        self.textSave3.setText('file3')
        self.tab6.layout.addWidget(self.textSave3, 2, 1)
        self.boxFormats3 = QComboBox(self)
        self.tab6.layout.addWidget(self.boxFormats3, 2, 2)
        self.textDPI3 = QLineEdit(self)
        self.textDPI3.setText('300 dpi')
        self.tab6.layout.addWidget(self.textDPI3, 2, 3)
        self.btnSaveMap3 = QPushButton('Сохранить', self)
        self.tab6.layout.addWidget(self.btnSaveMap3, 2, 4)
        # self.btnSaveMap3.clicked.connect(self.Save3)

        self.labSave4 = QLabel('Температурный профиль', self)
        self.tab6.layout.addWidget(self.labSave4, 3, 0)
        self.textSave4 = QLineEdit(self)
        self.textSave4.setText('file4')
        self.tab6.layout.addWidget(self.textSave4, 3, 1)
        self.boxFormats4 = QComboBox(self)
        self.tab6.layout.addWidget(self.boxFormats4, 3, 2)
        self.textDPI4 = QLineEdit(self)
        self.textDPI4.setText('300 dpi')
        self.tab6.layout.addWidget(self.textDPI4, 3, 3)
        self.btnSaveMap4 = QPushButton('Сохранить', self)
        self.tab6.layout.addWidget(self.btnSaveMap4, 3, 4)
        # self.btnSaveMap4.clicked.connect(self.Save4)

        self.labSave5 = QLabel('STA/LTA профиль', self)
        self.tab6.layout.addWidget(self.labSave5, 4, 0)
        self.textSave5 = QLineEdit(self)
        self.textSave5.setText('file5')
        self.tab6.layout.addWidget(self.textSave5, 4, 1)
        self.boxFormats5 = QComboBox(self)
        self.tab6.layout.addWidget(self.boxFormats5, 4, 2)
        self.textDPI5 = QLineEdit(self)
        self.textDPI5.setText('300 dpi')
        self.tab6.layout.addWidget(self.textDPI5, 4, 3)
        self.btnSaveMap5 = QPushButton('Сохранить', self)
        self.tab6.layout.addWidget(self.btnSaveMap5, 4, 4)
        # self.btnSaveMap5.clicked.connect(self.Save5)

        self.labSave6 = QLabel('Интегральный профиль', self)
        self.tab6.layout.addWidget(self.labSave6, 5, 0)
        self.textSave6 = QLineEdit(self)
        self.textSave6.setText('file6')
        self.tab6.layout.addWidget(self.textSave6, 5, 1)
        self.boxFormats6 = QComboBox(self)
        self.tab6.layout.addWidget(self.boxFormats6, 5, 2)
        self.textDPI6 = QLineEdit(self)
        self.textDPI6.setText('300 dpi')
        self.tab6.layout.addWidget(self.textDPI6, 5, 3)
        self.btnSaveMap6 = QPushButton('Сохранить', self)
        self.tab6.layout.addWidget(self.btnSaveMap6, 5, 4)
        # self.btnSaveMap6.clicked.connect(self.Save6)

        imgFormats = ['.tiff', '.png', '.eps', '.jpeg', '.ps', '.raw', '.svg']

        for form in imgFormats:
            self.boxFormats1.addItem(form)
            self.boxFormats2.addItem(form)
            self.boxFormats3.addItem(form)
            self.boxFormats4.addItem(form)
            self.boxFormats5.addItem(form)
            self.boxFormats6.addItem(form)
        ######## ОСНОВНЫЕ СВОЙСТВА ВКЛАДОК НАСТРОЙКИ ################

        self.tabsOptions = QTabWidget(self)
        self.tabsOptions.move(20, 300)
        self.tabsOptions.resize(300, 300)

        self.tabLines = QWidget(self)
        self.tabMark = QWidget(self)
        self.tabMap = QWidget(self)
        self.tabLimits = QWidget(self)

        self.tabsOptions.addTab(self.tabLines, 'Линии')
        self.tabsOptions.addTab(self.tabMark, 'Маркеры')
        self.tabsOptions.addTab(self.tabMap, 'Карта')
        self.tabsOptions.addTab(self.tabLimits, 'Границы')

        self.tabLines.layout = QGridLayout(self.tabLines)
        self.tabLines.setLayout(self.tabLines.layout)
        self.tabMap.layout = QGridLayout(self.tabMap)
        self.tabMap.setLayout(self.tabMap.layout)
        self.tabMark.layout = QGridLayout(self.tabMark)
        self.tabMark.setLayout(self.tabMark.layout)
        self.tabLimits.layout = QGridLayout(self.tabLimits)
        self.tabLimits.setLayout(self.tabLimits.layout)

        ############### Вкладка: Свойства линий #####################

        self.labPlot1Wid = QLabel('Толщина линий(График 1)', self)
        self.tabLines.layout.addWidget(self.labPlot1Wid, 0, 0)
        self.labPlot2Wid = QLabel('Толщина линий(График 2)', self)
        self.tabLines.layout.addWidget(self.labPlot2Wid, 3, 0)
        self.labPlot3Wid = QLabel('Толщина линий(График 3)', self)
        self.tabLines.layout.addWidget(self.labPlot3Wid, 6, 0)
        self.labPlot1Col = QLabel('Цвета линий(График 1)', self)
        self.tabLines.layout.addWidget(self.labPlot1Col, 0, 3)
        self.labPlot2Col = QLabel('Цвета линий(График 2)', self)
        self.tabLines.layout.addWidget(self.labPlot2Col, 3, 3)
        self.labPlot3Col = QLabel('Цвета линий(График 3)', self)
        self.tabLines.layout.addWidget(self.labPlot3Col, 6, 3)
        self.textPlot1Line1Width = QLineEdit(self)
        self.textPlot1Line1Width.setText('1')
        self.tabLines.layout.addWidget(self.textPlot1Line1Width, 1, 0)
        self.textPlot1Line2Width = QLineEdit(self)
        self.textPlot1Line2Width.setText('1')
        self.tabLines.layout.addWidget(self.textPlot1Line2Width, 2, 0)
        self.textPlot2Line1Width = QLineEdit(self)
        self.textPlot2Line1Width.setText('0.8')
        self.tabLines.layout.addWidget(self.textPlot2Line1Width, 4, 0)
        self.textPlot2Line2Width = QLineEdit(self)
        self.textPlot2Line2Width.setText('0.8')
        self.tabLines.layout.addWidget(self.textPlot2Line2Width, 5, 0)
        self.textPlot3Line1Width = QLineEdit(self)
        self.textPlot3Line1Width.setText('0.8')
        self.tabLines.layout.addWidget(self.textPlot3Line1Width, 7, 0)
        self.textPlot3Line2Width = QLineEdit(self)
        self.textPlot3Line2Width.setText('0.8')
        self.tabLines.layout.addWidget(self.textPlot3Line2Width, 8, 0)
        self.boxPlot1Line1Color = QComboBox(self)
        self.tabLines.layout.addWidget(self.boxPlot1Line1Color, 1, 3)
        self.boxPlot1Line2Color = QComboBox(self)
        self.tabLines.layout.addWidget(self.boxPlot1Line2Color, 2, 3)
        self.boxPlot2Line1Color = QComboBox(self)
        self.tabLines.layout.addWidget(self.boxPlot2Line1Color, 4, 3)
        self.boxPlot2Line2Color = QComboBox(self)
        self.tabLines.layout.addWidget(self.boxPlot2Line2Color, 5, 3)
        self.boxPlot3Line1Color = QComboBox(self)
        self.tabLines.layout.addWidget(self.boxPlot3Line1Color, 7, 3)
        self.boxPlot3Line2Color = QComboBox(self)
        self.tabLines.layout.addWidget(self.boxPlot3Line2Color, 8, 3)

        ############### Вкладка: Свойства маркеров #####################
        self.labMark = QLabel('Размеры маркеров(График 2)', self)
        self.tabMark.layout.addWidget(self.labMark, 0, 0, 1, 4)
        self.markW = QLineEdit(self)
        self.markW.setText('1')
        self.tabMark.layout.addWidget(self.markW, 1, 0)
        self.markW2 = QLineEdit(self)
        self.markW2.setText('1')
        self.boxcol = QComboBox(self)
        self.tabMark.layout.addWidget(self.boxcol, 1, 1)
        self.boxcol2 = QComboBox(self)
        self.tabMark.layout.addWidget(self.boxcol2, 1, 3)
        self.labMark2 = QLabel('Форма маркеров(График 2)', self)
        self.tabMark.layout.addWidget(self.labMark2, 2, 0, 1, 4)
        self.tabMark.layout.addWidget(self.markW2, 1, 2)
        self.boxMark = QComboBox(self)
        self.tabMark.layout.addWidget(self.boxMark, 3, 0, 1, 2)
        self.boxMark2 = QComboBox(self)
        self.tabMark.layout.addWidget(self.boxMark2, 3, 2, 1, 2)
        self.labMark3 = QLabel('Размеры маркеров(График 3)', self)
        self.tabMark.layout.addWidget(self.labMark3, 4, 0, 1, 4)
        self.markW3 = QLineEdit(self)
        self.markW3.setText('1')
        self.tabMark.layout.addWidget(self.markW3, 5, 0)
        self.markW4 = QLineEdit(self)
        self.markW4.setText('1')
        self.tabMark.layout.addWidget(self.markW4, 5, 2)
        self.labMark3 = QLabel('Форма маркеров(График 3)', self)
        self.tabMark.layout.addWidget(self.labMark3, 6, 0, 1, 4)
        self.boxcol3 = QComboBox(self)
        self.tabMark.layout.addWidget(self.boxcol3, 5, 1)
        self.boxcol4 = QComboBox(self)
        self.tabMark.layout.addWidget(self.boxcol4, 5, 3)
        self.boxMark3 = QComboBox(self)
        self.tabMark.layout.addWidget(self.boxMark3, 7, 0, 1, 2)
        self.boxMark4 = QComboBox(self)
        self.tabMark.layout.addWidget(self.boxMark4, 7, 2, 1, 2)

        markForm = [
            ' Нет маркеров',
            '.-точка',
            'o-окружность',
            ',-пиксель',
            'v',
            '^',
            '>',
            '<',
            's-квадрат',
            'p-пятиуг.',
            '*-звезда',
            'h-шестиуг.',
            '+',
            'x',
            'd-ромб',
        ]
        for i in markForm:
            self.boxMark.addItem(i)
            self.boxMark2.addItem(i)
            self.boxMark3.addItem(i)
            self.boxMark4.addItem(i)

        ########### Вкладка: Свойства Карты ##############
        self.labisC = QLabel('Коэффициент корреляции', self)
        self.tabMap.layout.addWidget(self.labisC, 0, 0, 1, 2)
        self.isC = QCheckBox(self)
        self.isC.setChecked(True)
        self.tabMap.layout.addWidget(self.isC, 0, 2)
        self.cmapBox = QComboBox(self)
        self.tabMap.layout.addWidget(self.cmapBox, 0, 3, 1, 2)
        for cmap_id in plt.colormaps():
            self.cmapBox.addItem(cmap_id)
            self.cmapBox2.addItem(cmap_id)
        self.cmapBox.setCurrentText('coolwarm')
        self.cmapBox2.setCurrentText('coolwarm')
        self.labGr = QLabel('Верхняя граница', self)
        self.tabMap.layout.addWidget(self.labGr, 1, 0, 1, 2)
        self.top1 = QLineEdit(self)
        self.top1.setText('1.5')
        self.tabMap.layout.addWidget(self.top1, 2, 0, 1, 1)
        self.labGr4 = QLabel('Нижняя граница(Карта 1)', self)
        self.tabMap.layout.addWidget(self.labGr4, 1, 2, 1, 3)
        self.bot1 = QLineEdit(self)
        self.bot1.setText('-1.5')
        self.tabMap.layout.addWidget(self.bot1, 2, 2, 1, 1)
        self.labGr2 = QLabel('Верхняя граница', self)
        self.tabMap.layout.addWidget(self.labGr2, 3, 0, 1, 2)
        self.top2 = QLineEdit(self)
        self.top2.setText('1.8')
        self.tabMap.layout.addWidget(self.top2, 4, 0, 1, 1)
        self.labGr5 = QLabel('Нижняя граница(Карта 2)', self)
        self.tabMap.layout.addWidget(self.labGr5, 3, 2, 1, 3)
        self.bot2 = QLineEdit(self)
        self.bot2.setText('-0.2')
        self.tabMap.layout.addWidget(self.bot2, 4, 2, 1, 1)
        self.labGr3 = QLabel('Верхняя граница', self)
        self.tabMap.layout.addWidget(self.labGr3, 5, 0, 1, 2)
        self.top3 = QLineEdit(self)
        self.top3.setText('1.8')
        self.tabMap.layout.addWidget(self.top3, 6, 0, 1, 1)
        self.labGr6 = QLabel('Нижняя граница(Карта 2)', self)
        self.tabMap.layout.addWidget(self.labGr6, 5, 2, 1, 3)
        self.bot3 = QLineEdit(self)
        self.bot3.setText('-0.2')
        self.tabMap.layout.addWidget(self.bot3, 6, 2, 1, 1)
        self.crclLabel = QLabel('Эпицентр', self)
        self.crclLabelLon = QLabel('Долгота', self)
        self.crclLabelLat = QLabel('Широта', self)
        self.tabMap.layout.addWidget(self.crclLabelLat, 8, 0)
        self.tabMap.layout.addWidget(self.crclLabelLon, 8, 2)
        self.tabMap.layout.addWidget(self.crclLabel, 7, 0)
        self.crcLat = QComboBox(self)
        self.tabMap.layout.addWidget(self.crcLat, 8, 1)
        self.crcLon = QComboBox(self)
        self.tabMap.layout.addWidget(self.crcLon, 8, 3, 1, 2)

        self.crclLabelColor = QLabel('Цвет', self)
        self.tabMap.layout.addWidget(self.crclLabelColor, 9, 0)
        self.crclLabelSize = QLabel('Размер', self)
        self.tabMap.layout.addWidget(self.crclLabelSize, 9, 2)

        self.boxCrclColor = QComboBox(self)
        self.tabMap.layout.addWidget(self.boxCrclColor, 9, 1)

        self.textCrclSize = QLineEdit(self)
        self.textCrclSize.setText('0.3 см')
        self.tabMap.layout.addWidget(self.textCrclSize, 9, 3)

        colors = ['b-синий', 'g-зеленый', 'r-красный', 'c-голубой', 'm-фиолетовый', 'y-желтый', 'k-черный']
        for color in colors:
            self.boxPlot1Line1Color.addItem(color)
            self.boxPlot1Line2Color.addItem(color)
            self.boxPlot2Line1Color.addItem(color)
            self.boxPlot2Line2Color.addItem(color)
            self.boxPlot3Line1Color.addItem(color)
            self.boxPlot3Line2Color.addItem(color)
            self.boxcol.addItem(color)
            self.boxcol2.addItem(color)
            self.boxcol3.addItem(color)
            self.boxcol4.addItem(color)
            self.boxCrclColor.addItem(color)

        self.boxPlot1Line1Color.setCurrentIndex(0)
        self.boxPlot1Line2Color.setCurrentIndex(1)
        self.boxPlot2Line2Color.setCurrentIndex(2)
        self.boxPlot3Line1Color.setCurrentIndex(3)
        self.boxPlot3Line2Color.setCurrentIndex(5)
        self.boxPlot2Line1Color.setCurrentIndex(4)
        self.boxDates.view().setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)

        ###############Вкладка: Свойства границ ######################
        self.labLimit1 = QLabel('Границы карты(широта/долгота)', self)
        self.labLimit2 = QLabel('Границы карты(широта/высота)', self)
        self.labLimit3 = QLabel('Границы карты(высота/долгота)', self)
        self.labLimit4 = QLabel('Границы Темп. профиля', self)
        self.labLimit5 = QLabel('Границы STA/LTA проф.', self)
        self.labLimit6 = QLabel('Границы Интег. профиля', self)

        self.tabLimits.layout.addWidget(self.labLimit1, 0, 0, 1, 4)
        self.tabLimits.layout.addWidget(self.labLimit2, 2, 0, 1, 4)
        self.tabLimits.layout.addWidget(self.labLimit3, 4, 0, 1, 4)
        self.tabLimits.layout.addWidget(self.labLimit4, 6, 0, 1, 4)
        self.tabLimits.layout.addWidget(self.labLimit5, 8, 0, 1, 4)
        self.tabLimits.layout.addWidget(self.labLimit6, 10, 0, 1, 4)

        self.boxLatMin1 = QComboBox(self)
        self.tabLimits.layout.addWidget(self.boxLatMin1, 1, 0, 1, 1)
        self.boxLatMax1 = QComboBox(self)
        self.tabLimits.layout.addWidget(self.boxLatMax1, 1, 1, 1, 1)
        self.boxLonMin1 = QComboBox(self)
        self.tabLimits.layout.addWidget(self.boxLonMin1, 1, 2, 1, 1)
        self.boxLonMax1 = QComboBox(self)
        self.tabLimits.layout.addWidget(self.boxLonMax1, 1, 3, 1, 1)
        self.boxLatMin2 = QComboBox(self)
        self.tabLimits.layout.addWidget(self.boxLatMin2, 3, 0, 1, 1)
        self.boxLatMax2 = QComboBox(self)
        self.tabLimits.layout.addWidget(self.boxLatMax2, 3, 1, 1, 1)
        self.boxLevMin1 = QComboBox(self)
        self.tabLimits.layout.addWidget(self.boxLevMin1, 3, 2, 1, 1)
        self.boxLevMax1 = QComboBox(self)
        self.tabLimits.layout.addWidget(self.boxLevMax1, 3, 3, 1, 1)
        self.boxLevMin2 = QComboBox(self)
        self.tabLimits.layout.addWidget(self.boxLevMin2, 5, 0, 1, 1)
        self.boxLevMax2 = QComboBox(self)
        self.tabLimits.layout.addWidget(self.boxLevMax2, 5, 1, 1, 1)
        self.boxLonMin2 = QComboBox(self)
        self.tabLimits.layout.addWidget(self.boxLonMin2, 5, 2, 1, 1)
        self.boxLonMax2 = QComboBox(self)
        self.tabLimits.layout.addWidget(self.boxLonMax2, 5, 3, 1, 1)

        self.boxDatesMinPlot1 = QComboBox(self)
        self.tabLimits.layout.addWidget(self.boxDatesMinPlot1, 7, 0, 1, 2)
        self.boxDatesMaxPlot1 = QComboBox(self)
        self.tabLimits.layout.addWidget(self.boxDatesMaxPlot1, 7, 2, 1, 2)
        self.boxDatesMinPlot2 = QComboBox(self)
        self.tabLimits.layout.addWidget(self.boxDatesMinPlot2, 9, 0, 1, 2)
        self.boxDatesMaxPlot2 = QComboBox(self)
        self.tabLimits.layout.addWidget(self.boxDatesMaxPlot2, 9, 2, 1, 2)
        self.boxDatesMinPlot3 = QComboBox(self)
        self.tabLimits.layout.addWidget(self.boxDatesMinPlot3, 11, 0, 1, 2)
        self.boxDatesMaxPlot3 = QComboBox(self)
        self.tabLimits.layout.addWidget(self.boxDatesMaxPlot3, 11, 2, 1, 2)

        self.filedialog = QFileDialog()
        self.setGeometry(0, 0, 1300, 700)
        self.setWindowTitle('Algorithm')
        self.show()

if __name__.endswith('__main__'):
    app = QApplication(sys.argv)
    ex = App()
    sys.exit(app.exec_())